### ISSUE TITLE
能不能定时更新一下

### ISSUE THREAD

**Issue by LEXUGE** [purocean/developer.pebble.com#1]
5个月过去了，备份是否该更新了？

**Comment by purocean** [comment]
pebble 都倒闭了不知道官方还能更新什么文档。不过前几天客户端更新了，貌似没看到有 api 更新的地方。所以不更了。

**Comment by LEXUGE** [comment]
如果可以，还是更新一下吧，作为开发者，我还是希望您能坚持到2017结束，为未来的社区支持或自玩留个底

**Comment by purocean** [comment]
看哪天有空同步一下吧
